name: CI/CD Pipeline - Deploy Backend and Frontend

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout del código
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 3. Build Docker images
      - name: Build Docker images
        run: |
          # Build Backend
          docker build -t ${{ secrets.DOCKER_USERNAME }}/backend-image:latest ./backend
          # Build Frontend
          docker build -t ${{ secrets.DOCKER_USERNAME }}/frontend-image:latest ./frontend

      # 4. Push Docker images to Docker Hub
      - name: Push Docker images to Docker Hub
        run: |
          # Push Backend Image
          docker push ${{ secrets.DOCKER_USERNAME }}/backend-image:latest
          # Push Frontend Image
          docker push ${{ secrets.DOCKER_USERNAME }}/frontend-image:latest
      # 5. SSH into EC2 and Pull Docker Images
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/backend-image:latest
            docker pull ${{ secrets.DOCKER_USERNAME }}/frontend-image:latest
