name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout del código
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 3. Conexión SSH al EC2
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            # Descargar imágenes desde Docker Hub
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/backend-image:latest
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/frontend-image:latest

            # Detener contenedores antiguos (si los hay)
            sudo docker stop backend-container || true
            sudo docker rm backend-container || true
            sudo docker stop frontend-container || true
            sudo docker rm frontend-container || true

            # Iniciar nuevos contenedores
            sudo docker run -d --name backend-container -p 3000:3000 ${{ secrets.DOCKER_USERNAME }}/backend-image:latest
            sudo docker run -d --name frontend-container -p 80:80 ${{ secrets.DOCKER_USERNAME }}/frontend-image:latest
